### PR TITLE
Add support for baseURL in config

### PR DESCRIPTION
**Pull request by jakesjews**
This fixes calling ajax for the latest version when the app uses a baseURL.

### CODE REVIEW

**Comment by sethwebster** [comment]
Looks good, thank you for the contribution.

**Comment by jakesjews** [comment]
@sethwebster I'm actually not 100% sure what to add to the readme. This should be a transparent change to users since its reading baseURL from the ember config.

**Comment by sethwebster** [comment]
Gotcha. Thanks for the clarification.

**Comment by sethwebster** [comment]
Squashed and merged in dacd72713cd87b4f567cab3a0d89024f5e34d190.

**Pull request closed without merging**
