### PR TITLE
feat: Update to Octane & Add Service (breaking change)

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by bf4** [comment]
stale?

**Comment by knownasilya** [comment]
No. About to release

**Comment by rtablada** [comment]
@knownasilya any word on what's left here? We were discussing as a team and were looking to do a lot of the stuff incorporated in these changes as our own first party code. Would be nice to help contrib back here instead and not have to reinvent the wheel.

**Comment by knownasilya** [comment]
@rtablada v3 is now published

**Pull request merged**
